### ISSUE TITLE
Change XL Turbo HP Steam Turbine's recipe to use IV-tier alloy

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GTplusplus#130]
# Issue Title  
Change the XL Turbo HP Steam Turbine's recipe to use an IV-tier alloy like Nitinol-60.

Currently, the XL turbo HP turbine uses Zeron-100, an LuV alloy:

![image](https://user-images.githubusercontent.com/33518699/153899749-81bacb9b-9e2c-4472-90d7-f67597fe0f0a.png)

However, high-pressure steam is typically used as an IV power source, and carries you through LuV before you unlock plasma in ZPM. Reducing the tier to IV allows for the XL turbo HP turbine to be used in mid-IV. Nitinol-60 is an IV-tier alloy that would work perfectly for this.

The reinforced casings for XL turbo HP turbines currently use Nitinol-60. To keep them in line with the other XL turbo turbines, it might also be wise to reduce the casing alloy down to an EV-tier alloy, such as Incoloy-MA956.

## Game Environment
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used:  2.1.2.2QF2

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [X]    Using GT:NH/GT:New Horizons?
 - [X]    Single Player?
 - [ ]    Multi Player?

**Comment by Steelux8** [comment]
XL turbines are not meant to be made in the same tier where their base versions are usually created and used. As you mentioned, HP Large Steam Turbines are mostly used in IV, so the XL version should come some tiers after that. Since the XL turbines now have a 48x speed more, the controllers ought to be even more expensive, which means I will probably tier this at ZPM when I make the change.
